services:
  village-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: village-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - village-admin-backend_aldeiaviva_network

networks:
  village-admin-backend_aldeiaviva_network:
    external: true